# Generated by Django 4.1 on 2024-06-08 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('coordenadas', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('numero', models.CharField(max_length=10)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.barrio')),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.calle')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Padecimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='profile_pics/')),
                ('primario', models.BooleanField(default=False)),
                ('secundario', models.BooleanField(default=False)),
                ('terciario', models.BooleanField(default=False)),
                ('fecha_nac', models.DateField(null=True)),
                ('dni', models.CharField(max_length=20)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.casa')),
                ('pedecimientos', models.ManyToManyField(default='Ninguno', to='registros.padecimientos')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('coordenadas', models.CharField(max_length=75)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.provincia'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.distrito'),
        ),
    ]
