# Generated by Django 4.1 on 2024-06-12 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0005_cambiocontraseña_es_admin_usuarioadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
