# Generated by Django 4.1 on 2024-06-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_alter_usuarioadmin_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='pedecimientos',
            new_name='padecimientos',
        ),
    ]
