# Generated by Django 4.1 on 2024-06-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_rename_pedecimientos_persona_padecimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dosis',
            field=models.CharField(default='No', max_length=30),
        ),
        migrations.AddField(
            model_name='persona',
            name='medicamento',
            field=models.CharField(default='Ninguno', max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono_emergencia',
            field=models.CharField(default='No tiene', max_length=100),
        ),
    ]
